services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace/slide-bar:cached
    command: sleep infinity
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://slidebar_user:slidebar_pass@db:5432/slidebar?schema=public
      - NODE_ENV=development
    ports:
      - '3000:3000'
      - '3001:3001'
      - '5173:5173'
      - '5174:5174'
      - '9323:9323'

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: slidebar
      POSTGRES_USER: slidebar_user
      POSTGRES_PASSWORD: slidebar_pass
    ports:
      - '5432:5432'

volumes:
  postgres-data:
